workflows:
  qwatch-ios-android:
    name: Qwatch Build

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter analyze
      - flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk